spring:
  application:
    name: obsen-backend

  datasource:
    url: jdbc:postgresql://localhost:5439/obsen_sre_db
    username: obsen_user
    password: ${DB_PASSWORD:obsen_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7089/auth/realms/Obsen-Realm
          jwk-set-uri: http://localhost:7089/auth/realms/Obsen-Realm/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
      cors:
        allowed-origins: "http://localhost:5173"
        allowed-methods: "GET,POST,PUT,DELETE"
  endpoint:
    prometheus:
      enabled: true
      