spring:
  application:
    name: obsen-backend

  datasource:
    url: jdbc:postgresql://localhost:5439/obsen_sre_db
    username: obsen_user
    password: ${DB_PASSWORD:obsen_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          # Assurez-vous que cette URL est exactement celle fournie dans le Well-Known OpenID
          issuer-uri: http://localhost:7089/auth/realms/Obsen-realm

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
      cors:
        allowed-origins: "http://localhost:5173"
        allowed-methods: "GET,POST"
  endpoint:
    prometheus:
      enabled: true

# Propriétés personnalisées pour le Keycloak Client / AuthController
keycloak:
  auth-server-url: http://localhost:7089/auth
  realm: Obsen-realm
  resource: obsen-backend
  credentials:
    secret: "CUY3P7BicvT4QY08KbCKbaAPMNhY9rBY" # Renseignez le client secret si le client 'obsen-backend' est de type Confidential